apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-simples
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-simples
  template:
    metadata:
      labels:
        app: api-simples
    spec:
      containers:
        - name: api-simples
          image: rafdavis/guia-jenkins:{{tag}}
          ports:
            - containerPort: 4000