apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-simples
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-simples
  template:
    metadata:
      labels:
        app: api-simples
    spec:
      containers:
      - name: api-simples
        image: rafdavis/guia-jenkins:{{tag}}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-simples
spec:
  selector:
    app: api-simples
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer